name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    
    - name: Install Jekyll
      run: |
        gem install bundler jekyll
        bundle install
    
    - name: Build site
      run: bundle exec jekyll build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3 
